### ISSUE TITLE
Is the page missing some available projects?

### ISSUE THREAD

**Issue by ifraixedes** [pillarjs/pillarjs.github.io#5]
Hi guys,

I came across pillarjs, I've really like the idea.
Checking it for future implementations, I've realised that the website is missing in the list 4 available projects:
- router
- parseurl
- resolve-path
- cookies

All of them except, `cookies`, are in version 1.x

Do they have to be in the website or you want not to add to the list?

Thanks.

**Comment by dougwilson** [comment]
> Do they have to be in the website or you want not to add to the list?

I'll add them in a moment. They were missing because we were not vigilant :)

**Comment by dougwilson** [comment]
Ok, they're all added :)

**Comment by ifraixedes** [comment]
Great thanks ;D
